### ISSUE TITLE
Dashboard small improvements

### ISSUE THREAD

**Issue by PatGendre** [fabmob/tracemob-phone#10]
- Supprimer l'onglet Graphiques, 
- N'afficher qu'un seul indicateur CO2, n 'afficher que le nb de calories (sans aliment)
- traduire les noms des modes, changer les m/s en km/h

**Comment by iciatech-yprime** [comment]
version disponible en test

**Comment by PatGendre** [comment]
Dans le tableau de bord on peut encore supprimer le détail "Moyenne / Semaine dernière"

**Comment by PatGendre** [comment]
Suggestion : comme on a beaucoup moins de données, on pourrait arriver à tout mettre en défilement pour éviter à swiper sur le côté pour les indicateurs du bas.
Les modes ON_FOOT etc. restent à traduire.
Le texte Distance / Déplacement / Durée / Vitesse peut être mis soit tout au pluriel (à mon avis) soit tout au singulier.

**Comment by PatGendre** [comment]
Le bouton changer date pourrait être renommé "Indicateurs cumulés du DATE1 à DATE2"
, il faut en tout cas afficher les dates utilisées pour le calcul.
Pour l'instant si on choisit la même date début et fin, on obtient 0 -> à corriger et/ou en attendant préciser si pour obtenir les données du jour J il faut sélectionner J-1 / J ou J/J+1

**Comment by PatGendre** [comment]
Il faudrait aussi convertir les m/s en km/h dans la vue détaillée du journal.

**Comment by PatGendre** [comment]
- changer l'icone du tram

**Comment by PatGendre** [comment]
- à mon avis, supprimer l'icône "partager" en haut à gauche

**Comment by romainbenjamin** [comment]
- Supprimer l'onglet Graphiques : OK 

- N'afficher qu'un seul indicateur CO2 : OK
       - En faisant des comparaison avec le simulateur de l'ADEME, j'ai l'impression qu'il y a de grosses approximations dans le calcul de cette empreinte carbone. On voit par exemple ci-dessous que pour 297km de voiture + 604km de "Avion ou Train", j'ai produit 160kg CO2e, j'ai bien le réglage de "Carbon Dataset" sur FR.
![photo_2021-05-05_16-49-58](https://user-images.githubusercontent.com/79320593/117161156-fbd0f180-adc1-11eb-81c6-a382f3dafd69.jpg)
       - Or, lorsque je simule sur monimpacttransport.fr, je produis 57.3 kg CO2e pour 297km de voiture et 1kg CO2e pour 604 km de train (et 138.9kg CO2e si c'était en avion). 
       - Est-ce que, lorsque le mode identifié est "Air or HSR", l'application sélectionne automatiquement l'avion pour le calcul d'empreinte carbone alors que j'ai requalifié mon trajet en train? 

- n 'afficher que le nb de calories (sans aliment) : OK est-ce possible d'ajouter l'unité à côté du nombre de calories dépensées? 
       - à quoi correspond "Moyenne" lorsqu'on clique sur la flèche du bas? 
       - est-ce qu'à la place de "Semaine dernière", on ne pourrait pas afficher une explication du type : nombre de calories dépensées sur la période sélectionné? En effet, l'indicateur "Semaine dernière" n'a d'intérêt que si on sélectionne une semaine...

- traduire les noms des modes : NOK, sur l'onglet tableau de bord, je n'ai aucun mode de traduits. Sur l'onglet journal, lorsque je souhaite qualifier un trajet les modes sont bien en français (mais il y a toujours l'inscription "Scroll for more" qui est en anglais)
- changer les m/s en km/h : Ok sur l'onglet tableau de bord, NOK sur l'onglet journal lorsqu'on clique sur le détail d'un trajet

**Comment by PatGendre** [comment]
@romainbenjamin 

> - Est-ce que, lorsque le mode identifié est "Air or HSR", l'application sélectionne automatiquement l'avion pour le calcul d'empreinte carbone alors que j'ai requalifié mon trajet en train?

Renseigner le mode et le profil n'a aucun impact sur les indicateurs CO2, comme déjà expliqué.
Ce serait plus simple de revoir le seuil de vitesse avion vs TGV, à court terme. Et le TGV serait alors avec le mode train.

**Comment by PatGendre** [comment]
> à quoi correspond "Moyenne"  ... "Semaine dernière"

on propose de supprimer aussi ces indications, de ne garder qu'un seul indicateurs, comme pour le CO2

**Comment by iciatech-yprime** [comment]
Nouvelle version disponible en test

**Comment by PatGendre** [comment]
Ok pour moi :-)

**Comment by romainbenjamin** [comment]
Ok pour moi!

**Comment by romainbenjamin** [comment]
Ok pour moi
