### ISSUE TITLE
Public app with new graphic style and revised texts

### ISSUE THREAD

**Issue by PatGendre** [fabmob/tracemob-phone#18]
- Changement du logo de l'application
- Changement de l'écran de chargement de l'application (splashscreen)
- Changement de la couleur verte claire en bleu de La Rochelle et mise en place des CGU (avec lien vers https://lafabriquedesmobilites.fr/tracemob/cgu depuis l'app et la page de description du store)
- Mise en place de la génération automatique du token

**Comment by iciatech-yprime** [comment]
version disponible en test

**Comment by PatGendre** [comment]
Il y a un texte mal traduit (au moins sous android) qui dit "depuis que vous utilisez Android 10..." mais je ne le retrouve pas dans , peut-être parce que le repo github n'est pas encore à jour? Sinon Romain, Sylvain ou moi pourrons proposer les corrections directement sur github.

**Comment by romainbenjamin** [comment]
- Changement du logo de l'application : OK
- Changement de l'écran de chargement de l'application (splashscreen) : OK
- Changement de la couleur verte claire en bleu de La Rochelle et mise en place des CGU (avec lien vers https://lafabriquedesmobilites.fr/tracemob/cgu depuis l'app et la page de description du store) : 
       - Changement de couleur OK
       - Mise en place des CGU : lorsque je clique sur "View Privacy Policy" rien ne s'affiche, ni les [CGU résumé](https://docs.google.com/document/d/1k1Nz0qvgtJS9xDHXI1puNN3lkG1BDXS6Jj5n1TpFPNg/edit?usp=sharing), ni le lien vers [la page de la FabMob](https://lafabriquedesmobilites.fr/tracemob/cgu) (cf. pièce jointe)
![photo_2021-05-05_16-38-49](https://user-images.githubusercontent.com/79320593/117159243-697c1e00-adc0-11eb-9612-efe18f5bfd27.jpg)

- Mise en place de la génération automatique du token : OK 
- "Revised texts" sur Apple
       - Onglet journal : les étapes 2 et 3 de l'assistant (lorsqu'on clique sur le point d'interrogation) sont les mêmes : "Cliquez sur la carte pour + de détails."
       - Onglet tableau de bord : OK
       - Onglet profil : il reste le "View privacy Policy" à traduire en français

**Comment by iciatech-yprime** [comment]
Nouvelle version disponible en test

**Comment by PatGendre** [comment]
Ok, pour moi sauf peut être vérifier les traducs du consentement

**Comment by romainbenjamin** [comment]
- Mise en place des CGU dans l'onglet "Profil" : OK
- Revised texts : onglet journal OK, Politique de confidentialité OK

OK pour moi

**Comment by romainbenjamin** [comment]
OK pour moi
