### ISSUE TITLE
Broken README link

### ISSUE THREAD

**Issue by Tamir198** [fabmob/tracemob-phone#29]
Hey, I have found that "can be found in the docs" link:

![image](https://user-images.githubusercontent.com/34707669/143554095-23f73034-462d-4e58-9e24-6a461c609b3a.png)

is not working:

![image](https://user-images.githubusercontent.com/34707669/143554048-e364e4e9-f0c7-44c1-9e66-7a0eddb88849.png)

**Comment by TTalex** [comment]
Seems to be working now, thanks for the feedback !!
