### ISSUE TITLE
simplify CO2 dashboard

### ISSUE THREAD

**Issue by PatGendre** [fabmob/tracemob-phone#5]
n'imprimer qu'une seule valeur : l'estimation d'émission pour la période considérée.

Côté doc:
- les explications du calcul initial dans e-mission sont [dans une page html](https://github.com/e-mission/e-mission-server/blob/master/front/server/carbon_calc_details.html)    
- le code du [calcul de CO2 se fait côté serveur (en python)](https://github.com/e-mission/e-mission-server/blob/gis-based-mode-detection/emission/core/wrapper/user.py) puis est [affiché en js dans la partie commune front du serveur](https://github.com/e-mission/e-mission-server/blob/2177582fdea9a52faa8c1a238e62b111dbbcedba/front/common/cfc.compare.js)  
- le [code côté app est assez compliqué](https://github.com/e-mission/e-mission-phone/blob/master/www/js/metrics.js), côté serveur aussi : bien vérifier ce que ça calcule ce qu'il faut
- ressortir les coefficients utilisés pour les émissions par mode pour les mettre dans une page de doc externe destinée aux utilisateurs (ou à intégrer dans l'aide / manuel U de l'appli) ; il semble que les coeff soient en dur
- à noter que l'application était prévue pour que l'utilisateur saisisse le modèle de sa ou ses véhicules dans l'appli mais ce n'est pas utilisé? (en demander plus à Shankari)

**Comment by PatGendre** [comment]
- Il y a aussi un bouton "carbon-dataset" pour choisir les paramètres de calcul selon le pays : je propose de le supprimer et de mettre les paramètres "en dur" pour l'instant. Plus un lien ou l'explication du calcul dans l'aide en ligne.
- Lors du développement de [MECO2 à Berlin](https://github.com/open-source-lab-DFKI/meco2-server/), il a été ajouté la possibilité de choisir le jeu de paramètres en fonction du pays dans le profil (bouton "carbon data set"). Le code se trouve dans le script services.js

**Comment by PatGendre** [comment]
- traduire carbon dataset en "Paramètres calcul CO2"
- traduire "View privacy policy" en "Politique de confidentialité"

**Comment by PatGendre** [comment]
- supprimer le bouton "validation des conditions" : il semble obsolète
-

**Comment by PatGendre** [comment]
Ok pour moi

**Comment by romainbenjamin** [comment]
Ok pour moi
