### ISSUE TITLE
Simplify Calories Dashboard

### ISSUE THREAD

**Issue by PatGendre** [fabmob/tracemob-phone#6]
N'afficher que le nombre de calories (sans aliment)

Le code est ici : https://github.com/e-mission/e-mission-phone/blob/master/www/js/metrics.js

Récupérer les coefficients utilisés pour calculer les calories par mode pour les mettre dans la doc (manuel U / aide) de l'appli.

**Comment by iciatech-yprime** [comment]
version disponible en test

**Comment by PatGendre** [comment]
Dans le tableau de bord on peut encore supprimer le détail "Moyenne / Semaine dernière"

**Comment by romainbenjamin** [comment]
Je pense que ça pourrait être bien de supprimer le détail "Semaine dernière" étant donné que la semaine n'est pas la période de référence. 
Du coup, vu qu'on a juste l'indicateur de calories qui prend pas mal de place, est-ce qu'il serait possible de le réduire pour faire apparaître une explication de l'indicateur d'empreinte carbone?

**Comment by iciatech-yprime** [comment]
Nouvelle version disponible en test

**Comment by PatGendre** [comment]
ok pour moi

**Comment by romainbenjamin** [comment]
Ok pour moi !

**Comment by romainbenjamin** [comment]
Ok pour moi
