### ISSUE TITLE
show slider for the Dashboard metrics

### ISSUE THREAD

**Issue by PatGendre** [fabmob/tracemob-phone#7]
faire apparaitre le slider pour les indicateurs distance/déplacements/vitesse/durée

cf. le code pour affiche les métriques distance/durée/déplacements/vitesses par mode
https://github.com/e-mission/e-mission-phone/blob/master/www/js/metrics.js 

Il est possible que Loïc l'ait déjà fait pour l'ancien traceur :    
https://github.com/fabmob/e-mission-phone-fabmob

**Comment by iciatech-yprime** [comment]
version disponible en test

**Comment by PatGendre** [comment]
Suggestion : comme on a beaucoup moins de données, on pourrait arriver à tout mettre en défilement pour éviter à swiper sur le côté pour les indicateurs du bas.
Les modes ON_FOOT etc. restent à traduire.
Le texte Distance / Déplacement / Durée / Vitesse peut être mis soit tout au pluriel (à mon avis) soit tout au singulier.

**Comment by romainbenjamin** [comment]
Le slider amène de la lisibilité et se rapproche plus d'autres applications ou d'une sorte "d'état de l'art", je pense pas mal de le garder. 

Par contre, il est vrai que l'indicateur "Calories" prend beaucoup de place pour peu d'informations. Est-ce qu'on pourrait réduire la place qu'il prend pour ajouter des explications sur l'indicateur d'empreinte carbone (en ajoutant par exemple "carbone" après empreinte, en explicitant le calcul, les distances prises en compte...) ?

**Comment by PatGendre** [comment]
Ok pour moi, petit détail quand on a 8 modes renseignés, le petit picto à 4 points qui indique dans quelle fenêtre latérale on est, se superpose avec les indicateurs des 2 modes du bas. Il faudrait donc allonger un peu la fenêtre vers le bas.

**Comment by romainbenjamin** [comment]
Ok pour moi!

**Comment by romainbenjamin** [comment]
Ok pour moi
