### ISSUE TITLE
reorganise the Profile page

### ISSUE THREAD

**Issue by PatGendre** [fabmob/tracemob-phone#8]
- Changement de couleurs des boutons en bleu La Rochelle
- Suppression des boutons "thème sombre", "partager" et "vérifier les mises à jour"
- Renommer la "Dev Zone" en "Zone Technique"
- Bouton supprimer mes données (informe que les données sont automatiquement supprimées au bout de 30 jours après désinstallation
de l'application)
- Déplacement de tous les éléments du profil dans la "Zone Technique" sauf "Déconnexion", "Tracking activé", "Télécharger les données", "Supprimer les données", "Mes données" (renommé "Données pour le calcul des calories")
- Ajout des états du Wifi, du GPS, et des Données mobiles 
- Ajout d'un bouton permettant de finir le déplacement

**Comment by iciatech-yprime** [comment]
version disponible en test

**Comment by romainbenjamin** [comment]
- Changement de couleurs des boutons en bleu La Rochelle : bleu OK, mais sur fond jaune (je ne me rappelle pas si c'est ce qu'on s'était dit)
- Suppression des boutons "thème sombre", "partager" et "vérifier les mises à jour" : OK
- Renommer la "Dev Zone" en "Zone Technique" : 
- Bouton supprimer mes données (informe que les données sont automatiquement supprimées au bout de 30 jours après désinstallation de l'application) : OK
- Déplacement de tous les éléments du profil dans la "Zone Technique" sauf 
       - "Déconnexion" : **NOK**
       - "Tracking activé" : OK
       - "Télécharger les données **json**" : OK 
       - "Supprimer **mon compte et mes** données" : OK
       - "Mes données" (renommé "Données pour le calcul des calories") : NOK, je ne vois ces données que dans mon onglet Tableau de bord lorsque je clique sur "Calibrer"
- Ajout des états du Wifi, du GPS, et des Données mobiles : OK
- Ajout d'un bouton permettant de finir le déplacement : OK

**Comment by PatGendre** [comment]
> - "Déconnexion" : NOK

Nous avons volontairement enlevé le bouton car on ne souhaite pas que l'U se déconnecte (car sinon il perd son token) : soit il coupe le tracking, soit il désinstalle. Ok pour vous?

**Comment by romainbenjamin** [comment]
- Pour le point "déconnexion" : ok 
- Terme tracking à supprimer et remplacer par geolocalisation
- Notification en anglais lorsqu'on quitte l'application à traduire en français

**Comment by iciatech-yprime** [comment]
Nouvelle version disponible en test
=> Le problème de traduction de la notification sur iOS n'a pas été corrigé

**Comment by romainbenjamin** [comment]
Ok pour moi (mis à part la traduction de notification : je crois qu'elle est en français sur Android, c'est Fabien Bassereau de Cozy qui me disait cela)

**Comment by romainbenjamin** [comment]
Hello,
Un autre point pour la page profil : remplacer "tracking" par "Suivi"

**Comment by romainbenjamin** [comment]
Ok pour moi
