### ISSUE TITLE
Dashboard : Improve Datepicker

### ISSUE THREAD

**Issue by PatGendre** [fabmob/tracemob-phone#9]
- Enlever le filtre du sélecteur de date
- pouvoir choisir 1 seul jour 
- afficher les dates choisies

**Comment by PatGendre** [comment]
Le bouton changer date pourrait être renommé "Indicateurs cumulés du DATE1 à DATE2"
, il faut en tout cas afficher les dates utilisées pour le calcul.
Pour l'instant si on choisit la même date début et fin, on obtient 0 -> à corriger car si on sélectionne J/J+1 on obtient bien le total J plus J+1 (à 1ère vue en tout cas)

**Comment by PatGendre** [comment]
> je n'ai plus que la possibilité de choisir une date de début d'analyse et une date de fin, je suppose que c'est ok

oui ! (le filtre était un onglet supplémentaire dans le datepicker)

**Comment by iciatech-yprime** [comment]
Nouvelle version disponible en test

**Comment by PatGendre** [comment]
Il manque le "De" avant la 1ère date.
Le nb de jours doit être incrémenté de 1 (càd que ça affiche 0 quand on met la même date de début et fin).
A noter qu'en regardant mes stats sur 4 mois je suis allé en Corse en avion et la vitesse moyenne est de 398km/h donc pour discriminer avion et TGV il faudra mettre un seuil < 400 km/h, disons 350 par ex.

**Comment by romainbenjamin** [comment]
Je rejoins Patrick, autrement ok pour moi :)

**Comment by PatGendre** [comment]
Nouvelle version Ok pour moi, on peut fermer l'issue

**Comment by romainbenjamin** [comment]
Ok pour moi
